2025-01-08 19:17:13,918 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "E:\PycharmProjects\Module_12\tests_12_4.py", line 19, in test_run
    runner_ = rt.Runner(5)
  File "E:\PycharmProjects\Module_12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-08 19:17:13,920 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "E:\PycharmProjects\Module_12\tests_12_4.py", line 9, in test_walk
    runner_ = rt.Runner('test', -5)
  File "E:\PycharmProjects\Module_12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
